version: "3.9"

services:
  app:
    container_name: app
    build: app/
    working_dir:
      /usr/src/app
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - network
    env_file:
      - ./app/.env
    command: npm run start

  # Контейнер с базой данных
  db:
    container_name: db
    image: postgres:12-alpine
    #build: db_data/
    environment:
      #POSTGRES_DB: "mydb"
      POSTGRES_USER: "public_hysteria"
      POSTGRES_PASSWORD: "0666"
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
      PGDATA: /var/lib/postgresql/data/db_d
    volumes:
      - ./db_data:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - network
    restart: always

  rabbitmq:
    container_name: rabbitmq
    image:  rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - network

  broker:
    container_name: broker
    build: broker/
    working_dir:
      /usr/src/broker
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
    command: node index.js
    restart: always
    networks:
      - network

  ml_worker:
    container_name: ml_worker
    build: ml_worker/
    depends_on:
      - rabbitmq
    restart: always
    command: sh -c '/ml_worker/wait-for-it.sh rabbitmq:5672 --timeout=15 -- python3 /ml_worker/handle.py & python3 /ml_worker/rpc-server.py'
    networks:
      - network

volumes:
    db_data:


networks:
  network: {}

