--
-- NOTE:
--
-- File paths need to be edited. Search for $$PATH$$ and
-- replace it with the path to the directory containing
-- the extracted data files.
--
--
-- PostgreSQL database dump
--

-- Dumped from database version 14.6 (Homebrew)
-- Dumped by pg_dump version 14.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE test_db;
--
-- Name: test_db; Type: DATABASE; Schema: -; Owner: public_hysteria
--

CREATE DATABASE test_db WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'C';


ALTER DATABASE test_db OWNER TO public_hysteria;

\connect test_db

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: activities; Type: TABLE; Schema: public; Owner: public_hysteria
--

CREATE TABLE public.activities (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    "desc" text
);


ALTER TABLE public.activities OWNER TO public_hysteria;

--
-- Name: activities_id_seq; Type: SEQUENCE; Schema: public; Owner: public_hysteria
--

CREATE SEQUENCE public.activities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.activities_id_seq OWNER TO public_hysteria;

--
-- Name: activities_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: public_hysteria
--

ALTER SEQUENCE public.activities_id_seq OWNED BY public.activities.id;


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: public_hysteria
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO public_hysteria;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: public_hysteria
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: public_hysteria
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO public_hysteria;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: public_hysteria
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: public_hysteria
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO public_hysteria;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: public_hysteria
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: public_hysteria
--

CREATE TABLE public.categories (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    img character varying(255)
);


ALTER TABLE public.categories OWNER TO public_hysteria;

--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: public_hysteria
--

CREATE SEQUENCE public.categories_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.categories_id_seq OWNER TO public_hysteria;

--
-- Name: categories_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: public_hysteria
--

ALTER SEQUENCE public.categories_id_seq OWNED BY public.categories.id;


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: public_hysteria
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO public_hysteria;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: public_hysteria
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: public_hysteria
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO public_hysteria;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: public_hysteria
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: public_hysteria
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO public_hysteria;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: public_hysteria
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: public_hysteria
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO public_hysteria;

--
-- Name: enrolments; Type: TABLE; Schema: public; Owner: public_hysteria
--

CREATE TABLE public.enrolments (
    id integer NOT NULL,
    date timestamp with time zone NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    "userUid" integer,
    "activityId" integer
);


ALTER TABLE public.enrolments OWNER TO public_hysteria;

--
-- Name: enrolments_id_seq; Type: SEQUENCE; Schema: public; Owner: public_hysteria
--

CREATE SEQUENCE public.enrolments_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.enrolments_id_seq OWNER TO public_hysteria;

--
-- Name: enrolments_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: public_hysteria
--

ALTER SEQUENCE public.enrolments_id_seq OWNED BY public.enrolments.id;


--
-- Name: groups; Type: TABLE; Schema: public; Owner: public_hysteria
--

CREATE TABLE public.groups (
    id bigint NOT NULL,
    cat_1 character varying(255),
    cat_2 character varying(255),
    activity character varying(255),
    address text,
    okrug text,
    district text,
    "inPerson" boolean,
    schedule text,
    schedule_1 text,
    schedule_2 text,
    status character varying(255)
);


ALTER TABLE public.groups OWNER TO public_hysteria;

--
-- Name: groups_id_seq; Type: SEQUENCE; Schema: public; Owner: public_hysteria
--

CREATE SEQUENCE public.groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.groups_id_seq OWNER TO public_hysteria;

--
-- Name: groups_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: public_hysteria
--

ALTER SEQUENCE public.groups_id_seq OWNED BY public.groups.id;


--
-- Name: main_activity; Type: TABLE; Schema: public; Owner: public_hysteria
--

CREATE TABLE public.main_activity (
    id bigint NOT NULL,
    name character varying,
    cat_id bigint NOT NULL
);


ALTER TABLE public.main_activity OWNER TO public_hysteria;

--
-- Name: main_activity_id_seq; Type: SEQUENCE; Schema: public; Owner: public_hysteria
--

ALTER TABLE public.main_activity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_activity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_category; Type: TABLE; Schema: public; Owner: public_hysteria
--

CREATE TABLE public.main_category (
    id bigint NOT NULL,
    name character varying
);


ALTER TABLE public.main_category OWNER TO public_hysteria;

--
-- Name: main_category_id_seq; Type: SEQUENCE; Schema: public; Owner: public_hysteria
--

ALTER TABLE public.main_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_enrollment; Type: TABLE; Schema: public; Owner: public_hysteria
--

CREATE TABLE public.main_enrollment (
    id bigint NOT NULL,
    rating integer NOT NULL,
    duration double precision,
    activity_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.main_enrollment OWNER TO public_hysteria;

--
-- Name: main_enrollment_id_seq; Type: SEQUENCE; Schema: public; Owner: public_hysteria
--

ALTER TABLE public.main_enrollment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_enrollment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_user; Type: TABLE; Schema: public; Owner: public_hysteria
--

CREATE TABLE public.main_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(254) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL
);


ALTER TABLE public.main_user OWNER TO public_hysteria;

--
-- Name: main_user_groups; Type: TABLE; Schema: public; Owner: public_hysteria
--

CREATE TABLE public.main_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.main_user_groups OWNER TO public_hysteria;

--
-- Name: main_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: public_hysteria
--

ALTER TABLE public.main_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_user_id_seq; Type: SEQUENCE; Schema: public; Owner: public_hysteria
--

ALTER TABLE public.main_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_user_user_permissions; Type: TABLE; Schema: public; Owner: public_hysteria
--

CREATE TABLE public.main_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.main_user_user_permissions OWNER TO public_hysteria;

--
-- Name: main_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: public_hysteria
--

ALTER TABLE public.main_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: public_hysteria
--

CREATE TABLE public.roles (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public.roles OWNER TO public_hysteria;

--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: public_hysteria
--

CREATE SEQUENCE public.roles_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.roles_id_seq OWNER TO public_hysteria;

--
-- Name: roles_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: public_hysteria
--

ALTER SEQUENCE public.roles_id_seq OWNED BY public.roles.id;


--
-- Name: users; Type: TABLE; Schema: public; Owner: public_hysteria
--

CREATE TABLE public.users (
    uid bigint NOT NULL,
    "createdAt" text,
    gender character varying(255),
    birthdate character varying(255),
    address text
);


ALTER TABLE public.users OWNER TO public_hysteria;

--
-- Name: users_uid_seq; Type: SEQUENCE; Schema: public; Owner: public_hysteria
--

CREATE SEQUENCE public.users_uid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.users_uid_seq OWNER TO public_hysteria;

--
-- Name: users_uid_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: public_hysteria
--

ALTER SEQUENCE public.users_uid_seq OWNED BY public.users.uid;


--
-- Name: visitors; Type: TABLE; Schema: public; Owner: public_hysteria
--

CREATE TABLE public.visitors (
    id integer NOT NULL,
    ip character varying(255) NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public.visitors OWNER TO public_hysteria;

--
-- Name: visitors_id_seq; Type: SEQUENCE; Schema: public; Owner: public_hysteria
--

CREATE SEQUENCE public.visitors_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.visitors_id_seq OWNER TO public_hysteria;

--
-- Name: visitors_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: public_hysteria
--

ALTER SEQUENCE public.visitors_id_seq OWNED BY public.visitors.id;


--
-- Name: activities id; Type: DEFAULT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.activities ALTER COLUMN id SET DEFAULT nextval('public.activities_id_seq'::regclass);


--
-- Name: categories id; Type: DEFAULT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.categories ALTER COLUMN id SET DEFAULT nextval('public.categories_id_seq'::regclass);


--
-- Name: enrolments id; Type: DEFAULT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.enrolments ALTER COLUMN id SET DEFAULT nextval('public.enrolments_id_seq'::regclass);


--
-- Name: groups id; Type: DEFAULT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.groups ALTER COLUMN id SET DEFAULT nextval('public.groups_id_seq'::regclass);


--
-- Name: roles id; Type: DEFAULT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.roles ALTER COLUMN id SET DEFAULT nextval('public.roles_id_seq'::regclass);


--
-- Name: users uid; Type: DEFAULT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.users ALTER COLUMN uid SET DEFAULT nextval('public.users_uid_seq'::regclass);


--
-- Name: visitors id; Type: DEFAULT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.visitors ALTER COLUMN id SET DEFAULT nextval('public.visitors_id_seq'::regclass);


--
-- Data for Name: activities; Type: TABLE DATA; Schema: public; Owner: public_hysteria
--

COPY public.activities (id, name, "desc") FROM stdin;
\.
COPY public.activities (id, name, "desc") FROM '$$PATH$$/3803.dat';

--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: public_hysteria
--

COPY public.auth_group (id, name) FROM stdin;
\.
COPY public.auth_group (id, name) FROM '$$PATH$$/3776.dat';

--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: public_hysteria
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.
COPY public.auth_group_permissions (id, group_id, permission_id) FROM '$$PATH$$/3778.dat';

--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: public_hysteria
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
\.
COPY public.auth_permission (id, name, content_type_id, codename) FROM '$$PATH$$/3774.dat';

--
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: public_hysteria
--

COPY public.categories (id, name, img) FROM stdin;
\.
COPY public.categories (id, name, img) FROM '$$PATH$$/3805.dat';

--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: public_hysteria
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.
COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM '$$PATH$$/3792.dat';

--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: public_hysteria
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
\.
COPY public.django_content_type (id, app_label, model) FROM '$$PATH$$/3772.dat';

--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: public_hysteria
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
\.
COPY public.django_migrations (id, app, name, applied) FROM '$$PATH$$/3770.dat';

--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: public_hysteria
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.
COPY public.django_session (session_key, session_data, expire_date) FROM '$$PATH$$/3793.dat';

--
-- Data for Name: enrolments; Type: TABLE DATA; Schema: public; Owner: public_hysteria
--

COPY public.enrolments (id, date, "createdAt", "updatedAt", "userUid", "activityId") FROM stdin;
\.
COPY public.enrolments (id, date, "createdAt", "updatedAt", "userUid", "activityId") FROM '$$PATH$$/3795.dat';

--
-- Data for Name: groups; Type: TABLE DATA; Schema: public; Owner: public_hysteria
--

COPY public.groups (id, cat_1, cat_2, activity, address, okrug, district, "inPerson", schedule, schedule_1, schedule_2, status) FROM stdin;
\.
COPY public.groups (id, cat_1, cat_2, activity, address, okrug, district, "inPerson", schedule, schedule_1, schedule_2, status) FROM '$$PATH$$/3807.dat';

--
-- Data for Name: main_activity; Type: TABLE DATA; Schema: public; Owner: public_hysteria
--

COPY public.main_activity (id, name, cat_id) FROM stdin;
\.
COPY public.main_activity (id, name, cat_id) FROM '$$PATH$$/3782.dat';

--
-- Data for Name: main_category; Type: TABLE DATA; Schema: public; Owner: public_hysteria
--

COPY public.main_category (id, name) FROM stdin;
\.
COPY public.main_category (id, name) FROM '$$PATH$$/3784.dat';

--
-- Data for Name: main_enrollment; Type: TABLE DATA; Schema: public; Owner: public_hysteria
--

COPY public.main_enrollment (id, rating, duration, activity_id, user_id) FROM stdin;
\.
COPY public.main_enrollment (id, rating, duration, activity_id, user_id) FROM '$$PATH$$/3786.dat';

--
-- Data for Name: main_user; Type: TABLE DATA; Schema: public; Owner: public_hysteria
--

COPY public.main_user (id, password, last_login, is_superuser, username, is_staff, is_active, date_joined, email, first_name, last_name) FROM stdin;
\.
COPY public.main_user (id, password, last_login, is_superuser, username, is_staff, is_active, date_joined, email, first_name, last_name) FROM '$$PATH$$/3780.dat';

--
-- Data for Name: main_user_groups; Type: TABLE DATA; Schema: public; Owner: public_hysteria
--

COPY public.main_user_groups (id, user_id, group_id) FROM stdin;
\.
COPY public.main_user_groups (id, user_id, group_id) FROM '$$PATH$$/3788.dat';

--
-- Data for Name: main_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: public_hysteria
--

COPY public.main_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.
COPY public.main_user_user_permissions (id, user_id, permission_id) FROM '$$PATH$$/3790.dat';

--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: public_hysteria
--

COPY public.roles (id, name, "createdAt", "updatedAt") FROM stdin;
\.
COPY public.roles (id, name, "createdAt", "updatedAt") FROM '$$PATH$$/3799.dat';

--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: public_hysteria
--

COPY public.users (uid, "createdAt", gender, birthdate, address) FROM stdin;
\.
COPY public.users (uid, "createdAt", gender, birthdate, address) FROM '$$PATH$$/3801.dat';

--
-- Data for Name: visitors; Type: TABLE DATA; Schema: public; Owner: public_hysteria
--

COPY public.visitors (id, ip, "createdAt", "updatedAt") FROM stdin;
\.
COPY public.visitors (id, ip, "createdAt", "updatedAt") FROM '$$PATH$$/3797.dat';

--
-- Name: activities_id_seq; Type: SEQUENCE SET; Schema: public; Owner: public_hysteria
--

SELECT pg_catalog.setval('public.activities_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: public_hysteria
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: public_hysteria
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: public_hysteria
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 36, true);


--
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: public_hysteria
--

SELECT pg_catalog.setval('public.categories_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: public_hysteria
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 4, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: public_hysteria
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 9, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: public_hysteria
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 21, true);


--
-- Name: enrolments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: public_hysteria
--

SELECT pg_catalog.setval('public.enrolments_id_seq', 1, false);


--
-- Name: groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: public_hysteria
--

SELECT pg_catalog.setval('public.groups_id_seq', 1, false);


--
-- Name: main_activity_id_seq; Type: SEQUENCE SET; Schema: public; Owner: public_hysteria
--

SELECT pg_catalog.setval('public.main_activity_id_seq', 2, true);


--
-- Name: main_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: public_hysteria
--

SELECT pg_catalog.setval('public.main_category_id_seq', 1, true);


--
-- Name: main_enrollment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: public_hysteria
--

SELECT pg_catalog.setval('public.main_enrollment_id_seq', 4, true);


--
-- Name: main_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: public_hysteria
--

SELECT pg_catalog.setval('public.main_user_groups_id_seq', 1, false);


--
-- Name: main_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: public_hysteria
--

SELECT pg_catalog.setval('public.main_user_id_seq', 7, true);


--
-- Name: main_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: public_hysteria
--

SELECT pg_catalog.setval('public.main_user_user_permissions_id_seq', 1, false);


--
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: public_hysteria
--

SELECT pg_catalog.setval('public.roles_id_seq', 1, false);


--
-- Name: users_uid_seq; Type: SEQUENCE SET; Schema: public; Owner: public_hysteria
--

SELECT pg_catalog.setval('public.users_uid_seq', 1, false);


--
-- Name: visitors_id_seq; Type: SEQUENCE SET; Schema: public; Owner: public_hysteria
--

SELECT pg_catalog.setval('public.visitors_id_seq', 3, true);


--
-- Name: activities activities_pkey; Type: CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.activities
    ADD CONSTRAINT activities_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: enrolments enrolments_pkey; Type: CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.enrolments
    ADD CONSTRAINT enrolments_pkey PRIMARY KEY (id);


--
-- Name: enrolments enrolments_userUid_activityId_key; Type: CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.enrolments
    ADD CONSTRAINT "enrolments_userUid_activityId_key" UNIQUE ("userUid", "activityId");


--
-- Name: groups groups_pkey; Type: CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT groups_pkey PRIMARY KEY (id);


--
-- Name: main_activity main_activity_pkey; Type: CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.main_activity
    ADD CONSTRAINT main_activity_pkey PRIMARY KEY (id);


--
-- Name: main_category main_category_pkey; Type: CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.main_category
    ADD CONSTRAINT main_category_pkey PRIMARY KEY (id);


--
-- Name: main_enrollment main_enrollment_pkey; Type: CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.main_enrollment
    ADD CONSTRAINT main_enrollment_pkey PRIMARY KEY (id);


--
-- Name: main_user main_user_email_key; Type: CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.main_user
    ADD CONSTRAINT main_user_email_key UNIQUE (email);


--
-- Name: main_user_groups main_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.main_user_groups
    ADD CONSTRAINT main_user_groups_pkey PRIMARY KEY (id);


--
-- Name: main_user_groups main_user_groups_user_id_group_id_ae195797_uniq; Type: CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.main_user_groups
    ADD CONSTRAINT main_user_groups_user_id_group_id_ae195797_uniq UNIQUE (user_id, group_id);


--
-- Name: main_user main_user_pkey; Type: CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.main_user
    ADD CONSTRAINT main_user_pkey PRIMARY KEY (id);


--
-- Name: main_user_user_permissions main_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.main_user_user_permissions
    ADD CONSTRAINT main_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: main_user_user_permissions main_user_user_permissions_user_id_permission_id_96b9fadf_uniq; Type: CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.main_user_user_permissions
    ADD CONSTRAINT main_user_user_permissions_user_id_permission_id_96b9fadf_uniq UNIQUE (user_id, permission_id);


--
-- Name: main_user main_user_username_key; Type: CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.main_user
    ADD CONSTRAINT main_user_username_key UNIQUE (username);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (uid);


--
-- Name: visitors visitors_pkey; Type: CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.visitors
    ADD CONSTRAINT visitors_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: public_hysteria
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: public_hysteria
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: public_hysteria
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: public_hysteria
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: public_hysteria
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: public_hysteria
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: public_hysteria
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: public_hysteria
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: main_activity_cat_id_b72d252d; Type: INDEX; Schema: public; Owner: public_hysteria
--

CREATE INDEX main_activity_cat_id_b72d252d ON public.main_activity USING btree (cat_id);


--
-- Name: main_enrollment_activity_id_dd1a501e; Type: INDEX; Schema: public; Owner: public_hysteria
--

CREATE INDEX main_enrollment_activity_id_dd1a501e ON public.main_enrollment USING btree (activity_id);


--
-- Name: main_enrollment_user_id_4f6d8d12; Type: INDEX; Schema: public; Owner: public_hysteria
--

CREATE INDEX main_enrollment_user_id_4f6d8d12 ON public.main_enrollment USING btree (user_id);


--
-- Name: main_user_email_2597293b_like; Type: INDEX; Schema: public; Owner: public_hysteria
--

CREATE INDEX main_user_email_2597293b_like ON public.main_user USING btree (email varchar_pattern_ops);


--
-- Name: main_user_groups_group_id_a337ba62; Type: INDEX; Schema: public; Owner: public_hysteria
--

CREATE INDEX main_user_groups_group_id_a337ba62 ON public.main_user_groups USING btree (group_id);


--
-- Name: main_user_groups_user_id_df502602; Type: INDEX; Schema: public; Owner: public_hysteria
--

CREATE INDEX main_user_groups_user_id_df502602 ON public.main_user_groups USING btree (user_id);


--
-- Name: main_user_user_permissions_permission_id_cd2b56a3; Type: INDEX; Schema: public; Owner: public_hysteria
--

CREATE INDEX main_user_user_permissions_permission_id_cd2b56a3 ON public.main_user_user_permissions USING btree (permission_id);


--
-- Name: main_user_user_permissions_user_id_451ce57f; Type: INDEX; Schema: public; Owner: public_hysteria
--

CREATE INDEX main_user_user_permissions_user_id_451ce57f ON public.main_user_user_permissions USING btree (user_id);


--
-- Name: main_user_username_6330637b_like; Type: INDEX; Schema: public; Owner: public_hysteria
--

CREATE INDEX main_user_username_6330637b_like ON public.main_user USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_main_user_id; Type: FK CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_main_user_id FOREIGN KEY (user_id) REFERENCES public.main_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_activity main_activity_cat_id_b72d252d_fk_main_category_id; Type: FK CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.main_activity
    ADD CONSTRAINT main_activity_cat_id_b72d252d_fk_main_category_id FOREIGN KEY (cat_id) REFERENCES public.main_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_enrollment main_enrollment_activity_id_dd1a501e_fk_main_activity_id; Type: FK CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.main_enrollment
    ADD CONSTRAINT main_enrollment_activity_id_dd1a501e_fk_main_activity_id FOREIGN KEY (activity_id) REFERENCES public.main_activity(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_enrollment main_enrollment_user_id_4f6d8d12_fk_main_user_id; Type: FK CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.main_enrollment
    ADD CONSTRAINT main_enrollment_user_id_4f6d8d12_fk_main_user_id FOREIGN KEY (user_id) REFERENCES public.main_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_user_groups main_user_groups_group_id_a337ba62_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.main_user_groups
    ADD CONSTRAINT main_user_groups_group_id_a337ba62_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_user_groups main_user_groups_user_id_df502602_fk_main_user_id; Type: FK CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.main_user_groups
    ADD CONSTRAINT main_user_groups_user_id_df502602_fk_main_user_id FOREIGN KEY (user_id) REFERENCES public.main_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_user_user_permissions main_user_user_permi_permission_id_cd2b56a3_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.main_user_user_permissions
    ADD CONSTRAINT main_user_user_permi_permission_id_cd2b56a3_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_user_user_permissions main_user_user_permissions_user_id_451ce57f_fk_main_user_id; Type: FK CONSTRAINT; Schema: public; Owner: public_hysteria
--

ALTER TABLE ONLY public.main_user_user_permissions
    ADD CONSTRAINT main_user_user_permissions_user_id_451ce57f_fk_main_user_id FOREIGN KEY (user_id) REFERENCES public.main_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

